Repository UWB-Biocomputing/Graphitti, pull requests merged in 2022-05, with the labels that each got.

#322 Created workflow to manually publish gh-pages
  .github/workflows/publish-gh-pages.yml
  docs/Developer/GHActions.md
  docs/Developer/GHPages.md
Labels: enhancement

#334 Event Buffer and changes from the impacted classes
  Simulator/Connections/Neuro/ConnGrowth.cpp
  Simulator/Connections/Neuro/ConnGrowth_d.cu
  Simulator/Recorders/Hdf5Recorder.cpp
  Simulator/Recorders/Hdf5Recorder.h
  Simulator/Recorders/IRecorder.h
  Simulator/Recorders/XmlRecorder.cpp
  Simulator/Recorders/XmlRecorder.h
  Simulator/Vertices/EventBuffer.cpp
  Simulator/Vertices/EventBuffer.h
  Simulator/Vertices/Neuro/AllIFNeurons.cpp
  Simulator/Vertices/Neuro/AllIFNeurons_d.cu
  Simulator/Vertices/Neuro/AllIZHNeurons.cpp
  Simulator/Vertices/Neuro/AllIZHNeurons.h
  Simulator/Vertices/Neuro/AllLIFNeurons.cpp
  Simulator/Vertices/Neuro/AllLIFNeurons.h
  Simulator/Vertices/Neuro/AllSpikingNeurons.cpp
  Simulator/Vertices/Neuro/AllSpikingNeurons.h
Labels: cleanup, refactor, Recorders, cpu-version-refactor

#336 documentation :: Refactor :: EventBuffer.md
  docs/Developer/eventBuffering.md
Labels: documentation
