Repository UWB-Biocomputing/Graphitti, pull requests merged in 2023-08, with the labels that each got.

#493 Issue 395 edit Doxygen blocks in EventBuffer
  Simulator/Vertices/EventBuffer.h
Labels: documentation, cleanup

#486 [ISSUE-410] Check switches on edgeType and make sure they have default cases
  Simulator/Edges/Neuro/AllNeuroEdges.cpp
  Simulator/Edges/Neuro/AllSynapsesDeviceFuncs_d.cpp
Labels: cleanup

#488 [ISSUE 487] Hotfix for clearing cache in section 3 documentation
  docs/Testing/index.md
Labels: documentation

#508 [ISSUE-368] renamed unitTesting folder and added a output folder
  .gitignore
  CMakeLists.txt
  Testing/UnitTesting/ConnectionsFactoryTests.cpp
  Testing/UnitTesting/DeserializationTests.cpp
  Testing/UnitTesting/EdgeIndexMapTests.cpp
  Testing/UnitTesting/EdgesFactoryTests.cpp
  Testing/UnitTesting/FunctionNodeTests.cpp
  Testing/UnitTesting/InputManagerTests.cpp
  Testing/UnitTesting/LayoutFactoryTests.cpp
  Testing/UnitTesting/OperationManagerTestingClass.h
  Testing/UnitTesting/OperationManagerTests.cpp
  Testing/UnitTesting/RNGFactoryTests.cpp
  Testing/UnitTesting/RecorderFactoryTests.cpp
  Testing/UnitTesting/SerializationFileAccessTest.cpp
  Testing/UnitTesting/SerializationTests.cpp
  Testing/UnitTesting/SimulatorTests.cpp
  Testing/UnitTesting/TestOutput/README.md
  Testing/UnitTesting/VerticesFactoryTests.cpp
  Testing/UnitTesting/XmlRecorderTests.cpp
  build/Output/serial1.xml
  build/Output/serial2.xml
  docs/Developer/GoogleTestsTutorial.md
  docs/Testing/index.md
Labels: cleanup, testing
