Repository UWB-Biocomputing/Graphitti, pull requests merged in 2024-01, with the labels that each got.

#573 [ISSUE-502] add an abstract base class ,RecordableBase defining the interface for recordable variables
  Simulator/Recorders/Hdf5Recorder.cpp
  Simulator/Recorders/Hdf5Recorder.h
  Simulator/Recorders/Neuro/Hdf5GrowthRecorder.cpp
  Simulator/Recorders/Neuro/Hdf5GrowthRecorder.h
  Simulator/Recorders/Recordable.h
  Simulator/Recorders/RecordableBase.h
  Simulator/Recorders/Recorder.h
  Simulator/Recorders/XmlRecorder.cpp
  Simulator/Recorders/XmlRecorder.h
  Simulator/Vertices/EventBuffer.cpp
  Simulator/Vertices/EventBuffer.h
  Simulator/Vertices/Neuro/AllSpikingNeurons.cpp
  Simulator/Vertices/Neuro/AllSpikingNeurons.h
  Testing/UnitTesting/XmlRecorderTests.cpp
  docs/Developer/ClassDiagrams/recordable.puml
  docs/Developer/ClassDiagrams/recorder.puml
  docs/Developer/ClassDiagrams/vertices.puml
Labels: Recorders, testing, architecture

#583 [ISSUE-510] Remove redundant file
  docs/User/StudentSetup.md
  docs/index.md
Labels: documentation, good first issue, cleanup

#585 [ISSUE 576] Modified the secondary process in the cluster point process script
  Tools/InputGeneration/ClusterPointProcess/cluster_point_process_functions.py
Labels: NG911

#596 [ISSUE-586] Sequence Diagram Updates
  docs/Developer/SequenceDiagrams/diagrams/graphitti program flow.png
  docs/Developer/SequenceDiagrams/diagrams/graphitti program flow.svg
  docs/Developer/SequenceDiagrams/diagrams/simObjectsCreation.png
  docs/Developer/SequenceDiagrams/diagrams/simObjectsCreation.svg
  docs/Developer/SequenceDiagrams/diagrams/simulatorSetup.png
  docs/Developer/SequenceDiagrams/diagrams/simulatorSetup.svg
  docs/Developer/SequenceDiagrams/diagrams/simulatorSimulate.png
  docs/Developer/SequenceDiagrams/diagrams/simulatorSimulate.svg
  docs/Developer/SequenceDiagrams/diagrams/topLevelFlow.png
  docs/Developer/SequenceDiagrams/diagrams/topLevelFlow.svg
  docs/Developer/SequenceDiagrams/graphitti.puml
  docs/Developer/SequenceDiagrams/simObjectsCreation.puml
  docs/Developer/SequenceDiagrams/simulatorSetup.puml
  docs/Developer/SequenceDiagrams/simulatorSimulate.puml
  docs/Developer/SequenceDiagrams/topLevelFlow.puml
  docs/Developer/sequenceDiagrams.md
Labels: documentation, cleanup
