Repository UWB-Biocomputing/Graphitti, pull requests merged in 2024-06, with the labels that each got.

#494 [ISSUE 376] Rename command line options for stimulusfile (-s), deserializefile(-r) and serializefile(-w)
  Simulator/Core/Core.cpp
  docs/Developer/StudentSetup.md
  docs/User/quickstart.md
Labels: documentation, good first issue, cleanup

#647 [ISSUE 641] Use GraphML To Set Neuron Type
  Simulator/Layouts/Layout.cpp
  Simulator/Layouts/Neuro/LayoutNeuro.cpp
  Testing/RegressionTesting/configfiles/test-medium-connected-long.xml
  Testing/RegressionTesting/configfiles/test-medium-connected.xml
  Testing/RegressionTesting/configfiles/test-medium-long.xml
  Testing/RegressionTesting/configfiles/test-medium.xml
  Testing/RegressionTesting/configfiles/test-small-connected-long.xml
  Testing/RegressionTesting/configfiles/test-small-connected.xml
  Testing/RegressionTesting/configfiles/test-small-long.xml
  Testing/RegressionTesting/configfiles/test-small.xml
  Testing/RegressionTesting/configfiles/test-tiny.xml
  Tools/NeuroGraphGenerator.py
  configfiles/graphs/test-medium.graphml
  configfiles/graphs/test-small.graphml
  configfiles/graphs/test-tiny.graphml
Labels: refactor

#661 [ISSUE 652] Update Neural Docs
  Tools/NeuralGraphGeneration/NeuroGraphGenerator.py
  Tools/NeuralGraphGeneration/README.md
  configfiles/test-large-long.xml
  docs/Developer/index.md
  docs/User/configuration.md
Labels: documentation

#638 [ISSUE 270] Handle Nullptr From Factory
  Simulator/Core/Model.cpp
  Simulator/Core/Simulator.cpp
  Simulator/Layouts/Layout.cpp
Labels: bug, good first issue, cleanup, urgent, exception-handling, undergrad-capstone

#670 Issue 654 add implement hdf5 recorderconstructor
  CMakeLists.txt
  Simulator/Connections/Neuro/ConnGrowth.cpp
  Simulator/Recorders/Hdf5Recorder.cpp
  Simulator/Recorders/Hdf5Recorder.h
  Simulator/Recorders/Neuro/Hdf5GrowthRecorder.cpp
  Simulator/Recorders/Neuro/Hdf5GrowthRecorder.h
  Simulator/Recorders/Recorder.h
  Simulator/Utils/Factory.h
  Testing/UnitTesting/Hdf5RecorderTests.cpp
  Testing/UnitTesting/RecorderFactoryTests.cpp
  configfiles/test-medium-hdf5.xml
  configfiles/test-small-hdf5.xml
  configfiles/test-tiny-hdf5.xml
Labels: bug, Recorders
