Repository UWB-Biocomputing/Graphitti, pull requests merged in 2025-01, with the labels that each got.

#757 [hotfix-issue-756] Change test actions to work on any PR
  .github/workflows/format.yml
  .github/workflows/tests.yml
Labels: cleanup, urgent, testing

#758 [hotfix-issue-756] Apply hotfixes to SharedDevelopment
  .github/workflows/format.yml
  .github/workflows/tests.yml
  Tools/InputGeneration/README.md
  docs/Developer/GraphAndEventInputs.md
Labels: cleanup, urgent, testing

#755 [ISSUE 754] Add serial-File-Access-Test Removed During Serialization Test Update
  .gitignore
  Simulator/Edges/NG911/All911Edges.h
  Simulator/Edges/Neuro/AllDSSynapses_d.cpp
  Simulator/Edges/Neuro/AllDynamicSTDPSynapses_d.cpp
  Simulator/Edges/Neuro/AllNeuroEdges.cpp
  Simulator/Edges/Neuro/AllSTDPSynapses.cpp
  Simulator/Edges/Neuro/AllSTDPSynapses_d.cpp
  Simulator/Edges/Neuro/AllSpikingSynapses.cpp
  Simulator/Edges/Neuro/AllSpikingSynapses_d.cpp
  Simulator/Utils/Inputs/FSInput.cpp
  Simulator/Utils/Inputs/SInputPoisson.cpp
  Simulator/Utils/ParameterManager.cpp
  Testing/UnitTesting/SerializationFileAccessTest.cpp
  Testing/UnitTesting/XmlRecorderTests.cpp
Labels: bug, urgent

#767 [ISSUE-753] CMakeLists fixes
  CMakeLists.txt
Labels: GPU, cleanup
